name: my first pipeline
on: push main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: action/checkout@v4
     - name: build image
       run: docker build -t Mmutoni/ci_portifolio .
     - name: list images
       run: docker images